# Generated by Django 5.1.2 on 2025-11-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=40)),
                ('descripcion_curso', models.CharField(max_length=40)),
                ('fecha_inicio_curso', models.DateField()),
                ('fecha_fin_curso', models.DateField()),
            ],
        ),
    ]
