# Generated by Django 5.1.2 on 2025-12-08 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organizador',
            new_name='Organizacion',
        ),
    ]
