# Generated by Django 6.0 on 2025-12-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_evento_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
