# Generated by Django 5.1.2 on 2025-11-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_categoriaevento_evento_asistenteevento_inscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='limite_cupos',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='primer_dia',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], default='martes', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='ultimo_dia',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], default='jueves', max_length=20),
            preserve_default=False,
        ),
    ]
