# Generated by Django 5.1.2 on 2025-11-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_curso_destacado_curso_limite_cupos_curso_primer_dia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen_curso',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
