# Generated by Django 5.1.2 on 2025-11-14 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_noticias_curso_imagen_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='descripcion_noticia',
            field=models.CharField(default='Descripción pendiente', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticias',
            name='dia_de_notificacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticias',
            name='imagen_noticia',
            field=models.TextField(default='Sin imagen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticias',
            name='titulo_noticia',
            field=models.CharField(default='Titulo pendiente', max_length=40),
            preserve_default=False,
        ),
    ]
