# Generated by Django 5.1.2 on 2025-11-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_noticias_descripcion_noticia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
