# Generated by Django 5.1.2 on 2025-12-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentariosnoticias',
            options={},
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen_curso',
            field=models.TextField(blank=True, null=True),
        ),
    ]
