# Generated by Django 5.1.2 on 2025-12-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('usuario', 'Usuario'), ('administrador', 'Administrador'), ('organizador', 'Organizador')], max_length=25),
        )
    ]
