# Generated by Django 5.1.2 on 2025-12-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_usuario_rol_delete_asistenteevento'),
    ]
