# Generated by Django 5.1.2 on 2025-12-08 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_evento_destacado_delete_asistenteevento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaEvento',
            new_name='Categoria',
        ),
    ]
