# Generated by Django 5.1.2 on 2025-12-08 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_categoriaevento_categoria_curso_categoria_and_more'),
    ]
