# Generated by Django 5.1.2 on 2025-12-08 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_asistenteevento'),
    ]

    operations = [
        
    ]
